{% set version = "2.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rsq
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rsq_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rsq/rsq_{{ version }}.tar.gz
  sha256: 6e9c58ba22d8d53de5cf491da229a8532abcdecf98484b4359c741d8b346c2e4

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-deriv
    - r-mass
    - r-matrix
    - r-lme4
    - r-nlme
  run:
    - r-base
    - r-deriv
    - r-mass
    - r-matrix
    - r-lme4
    - r-nlme

test:
  commands:
    - $R -e "library('rsq')"           # [not win]
    - "\"%R%\" -e \"library('rsq')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rsq
  license: GPL-2.0-only
  summary: Calculate generalized R-squared, partial R-squared, and partial correlation coefficients for generalized linear models (including quasi models with well defined variance functions).
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - PertuyF

# Package: rsq
# Title: R-Squared and Related Measures
# Version: 1.1
# Date: 2018-09-24
# Author: Dabao Zhang
# Maintainer: Dabao Zhang <zhangdb@stat.purdue.edu>
# Description: Calculate generalized R-squared, partial R-squared, and partial correlation coefficients for generalized linear models (including quasi models with well defined variance functions).
# Imports: methods, stats, MASS
# Suggests:
# License: GPL-2
# NeedsCompilation: no
# Packaged: 2018-09-26 00:05:48 UTC; zhangdb
# Repository: CRAN
# Date/Publication: 2018-09-27 13:30:03 UTC
