{% set version = "2.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rsq
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rsq_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rsq/rsq_{{ version }}.tar.gz
  sha256: f7e9da5b829f8226dbdb9b94c1afbb01403e9f02c56977570458876705cd6905

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-deriv
    - r-mass
    - r-matrix
    - r-deming
    - r-lme4
    - r-nlme
  run:
    - r-base
    - r-deriv
    - r-mass
    - r-matrix
    - r-deming
    - r-lme4
    - r-nlme

test:
  commands:
    - $R -e "library('rsq')"           # [not win]
    - "\"%R%\" -e \"library('rsq')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rsq
  license: GPL-2.0-or-later
  summary: Calculate generalized R-squared, partial R-squared, and partial correlation coefficients for generalized linear models (including quasi models with well defined variance functions).
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - PertuyF
